-- Character creation gained a canon origin and a narrative core.
--
-- These columns mirror `character.props`, the same way `name`, `archetype`,
-- `bio` and `tags` already do: `props` stays the source of truth and the DTO is
-- the enforcement point, so the mirrors are nullable and exist for querying.
--
-- The four canon ids deliberately carry no foreign key to `entity`. Canon is
-- corrected by reverting an ingest batch, which deletes entity rows; a
-- character reference must not be able to block that.

ALTER TABLE character
  ADD COLUMN species_id uuid,
  ADD COLUMN culture_id uuid,
  ADD COLUMN homeland_id uuid,
  ADD COLUMN allegiance_id uuid,
  ADD COLUMN allegiance_stance text,
  ADD COLUMN callings text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN drive text,
  ADD COLUMN flaw text,
  ADD COLUMN instinct text,
  ADD COLUMN unique_thing text;

ALTER TABLE character
  ADD CONSTRAINT character_allegiance_stance_check
  CHECK (allegiance_stance IS NULL
    OR allegiance_stance IN ('member', 'indebted', 'estranged', 'hunted'));

-- Characters authored before this migration carry no origin and no nature.
-- Neither can be reconstructed: origin needs four real canon entity ids and
-- nature needs authored prose. The narrator reads both unconditionally, so such
-- a character crashes the sheet on open and the turn graph on its next move.
-- They are dropped here, along with the chronicles played through them.
--
-- Everything else in the graph is regenerated by the deploy that runs this:
-- the seed step reapplies application configuration and world vocabulary, and
-- the canon-seed Lambda reapplies the authored world. Only play data is lost,
-- and only the play data that was already unplayable.
DELETE FROM node WHERE kind IN ('character', 'chronicle', 'chronicle_turn');
