import { z } from 'zod';
export const HardStateKind = z.enum([
    'location',
    'npc',
    'ship_or_vehicle',
    'artifact',
    'faction',
    'resource',
    'magic',
    'faith',
    'conflict',
    'rumor',
    'law_or_edict',
]);
export const HardStateSubkind = z.enum([
    'planet',
    'moon',
    'region',
    'city',
    'district',
    'shop_or_tavern',
    'habitat',
    'station',
    'space_anomaly',
    'site',
    'dungeon',
    'facility',
    'civilian',
    'leader',
    'ally',
    'notorious_villain',
    'agent',
    'merchant',
    'scholar',
    'captain',
    'mystic',
    'capital_ship',
    'frigate',
    'courier',
    'shuttle',
    'gunship',
    'lander',
    'walker',
    'train',
    'caravan',
    'relic',
    'weapon',
    'focus',
    'device',
    'data_relic',
    'key',
    'containment_relic',
    'government',
    'corporate',
    'outlaw',
    'guild',
    'order',
    'cartel',
    'militia',
    'strategic',
    'mundane',
    'hyperdrive_fuel',
    'spirit_dust',
    'ore',
    'data',
    'biomass',
    'school',
    'spell',
    'ritual',
    'tradition',
    'forbidden_technique',
    'religion',
    'cult',
    'philosophy',
    'mystery_cult',
    'state_church',
    'war',
    'rebellion',
    'insurgency',
    'cold_war',
    'proxy_war',
    'shadow_conflict',
    'local',
    'regional',
    'cosmic',
    'personal',
    'prophecy',
    'civil_law',
    'religious_law',
    'martial_law',
    'corporate_policy',
    'treaty',
]);
export const HardStateStatus = z.enum([
    'known',
    'hidden',
    'lost',
    'ruined',
    'destroyed',
    'alive',
    'dead',
    'missing',
    'retired',
    'ascended',
    'operational',
    'damaged',
    'mothballed',
    'intact',
    'broken',
    'sealed',
    'corrupted',
    'active',
    'fragmented',
    'dormant',
    'outlawed',
    'abundant',
    'common',
    'scarce',
    'depleted',
    'mythical',
    'sanctioned',
    'forbidden',
    'forgotten',
    'experimental',
    'dominant',
    'major',
    'minority',
    'heresy',
    'suppressed',
    'extinct',
    'brewing',
    'stalemated',
    'won',
    'frozen',
    'fresh',
    'spreading',
    'confirmed',
    'debunked',
    'drafted',
    'enacted',
    'contested',
    'ignored',
    'repealed',
]);
export const HardStateProminence = z.enum([
    'forgotten',
    'marginal',
    'recognized',
    'renowned',
    'mythic',
]);
export const HardStateLink = z.object({
    relationship: z.string().min(1),
    targetId: z.string().min(1),
    direction: z.enum(['out', 'in']),
});
export const HardState = z.object({
    id: z.string().min(1),
    slug: z.string().min(1),
    kind: HardStateKind,
    subkind: HardStateSubkind.optional(),
    name: z.string().min(1),
    description: z.string().max(2000).optional(),
    status: HardStateStatus.optional(),
    prominence: HardStateProminence.default('recognized'),
    links: z.array(HardStateLink).default([]),
    createdAt: z
        .number()
        .int()
        .nonnegative()
        .default(() => Date.now()),
    updatedAt: z
        .number()
        .int()
        .nonnegative()
        .default(() => Date.now()),
});
