import { z } from 'zod';

export const HardStateKind = z.enum([
  'location',
  'npc',
  'ship_or_vehicle',
  'artifact',
  'faction',
  'resource',
  'magic',
  'faith',
  'conflict',
  'rumor',
  'law_or_edict',
]);
export type HardStateKind = z.infer<typeof HardStateKind>;

export const HardStateSubkind = z.enum([
  'planet',
  'moon',
  'region',
  'city',
  'district',
  'shop_or_tavern',
  'habitat',
  'station',
  'space_anomaly',
  'site',
  'dungeon',
  'facility',
  'civilian',
  'leader',
  'ally',
  'notorious_villain',
  'agent',
  'merchant',
  'scholar',
  'captain',
  'mystic',
  'capital_ship',
  'frigate',
  'courier',
  'shuttle',
  'gunship',
  'lander',
  'walker',
  'train',
  'caravan',
  'relic',
  'weapon',
  'focus',
  'device',
  'data_relic',
  'key',
  'containment_relic',
  'government',
  'corporate',
  'outlaw',
  'guild',
  'order',
  'cartel',
  'militia',
  'strategic',
  'mundane',
  'hyperdrive_fuel',
  'spirit_dust',
  'ore',
  'data',
  'biomass',
  'school',
  'spell',
  'ritual',
  'tradition',
  'forbidden_technique',
  'religion',
  'cult',
  'philosophy',
  'mystery_cult',
  'state_church',
  'war',
  'rebellion',
  'insurgency',
  'cold_war',
  'proxy_war',
  'shadow_conflict',
  'local',
  'regional',
  'cosmic',
  'personal',
  'prophecy',
  'civil_law',
  'religious_law',
  'martial_law',
  'corporate_policy',
  'treaty',
]);
export type HardStateSubkind = z.infer<typeof HardStateSubkind>;

export const HardStateStatus = z.enum([
  'known',
  'hidden',
  'lost',
  'ruined',
  'destroyed',
  'alive',
  'dead',
  'missing',
  'retired',
  'ascended',
  'operational',
  'damaged',
  'mothballed',
  'intact',
  'broken',
  'sealed',
  'corrupted',
  'active',
  'fragmented',
  'dormant',
  'outlawed',
  'abundant',
  'common',
  'scarce',
  'depleted',
  'mythical',
  'sanctioned',
  'forbidden',
  'forgotten',
  'experimental',
  'dominant',
  'major',
  'minority',
  'heresy',
  'suppressed',
  'extinct',
  'brewing',
  'stalemated',
  'won',
  'frozen',
  'fresh',
  'spreading',
  'confirmed',
  'debunked',
  'drafted',
  'enacted',
  'contested',
  'ignored',
  'repealed',
]);
export type HardStateStatus = z.infer<typeof HardStateStatus>;

export const HardStateLink = z.object({
  relationship: z.string().min(1),
  targetId: z.string().min(1),
  direction: z.enum(['out', 'in']),
});
export type HardStateLink = z.infer<typeof HardStateLink>;

export const HardState = z.object({
  id: z.string().min(1),
  kind: HardStateKind,
  subkind: HardStateSubkind.optional(),
  name: z.string().min(1),
  status: HardStateStatus.optional(),
  links: z.array(HardStateLink).default([]),
  createdAt: z
    .number()
    .int()
    .nonnegative()
    .default(() => Date.now()),
  updatedAt: z
    .number()
    .int()
    .nonnegative()
    .default(() => Date.now()),
});

export type HardState = z.infer<typeof HardState>;
