import { z } from 'zod';
export declare const TurnProgressPayloadSchema: z.ZodObject<{
    advancesTimeline: z.ZodOptional<z.ZodBoolean>;
    beatTracker: z.ZodOptional<z.ZodObject<{
        focusBeatId: z.ZodNullable<z.ZodString>;
        newBeat: z.ZodNullable<z.ZodObject<{
            title: z.ZodString;
            description: z.ZodString;
        }, z.core.$strip>>;
        updates: z.ZodArray<z.ZodObject<{
            beatId: z.ZodString;
            changeKind: z.ZodEnum<{
                advance: "advance";
                resolve: "resolve";
            }>;
            description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
            status: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
                in_progress: "in_progress";
                succeeded: "succeeded";
                failed: "failed";
            }>>>;
        }, z.core.$strip>>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
    chronicleShouldClose: z.ZodOptional<z.ZodBoolean>;
    executedNodes: z.ZodOptional<z.ZodArray<z.ZodString>>;
    failure: z.ZodOptional<z.ZodBoolean>;
    gmMessage: z.ZodOptional<z.ZodObject<{
        content: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        role: z.ZodEnum<{
            player: "player";
            gm: "gm";
            system: "system";
        }>;
    }, z.core.$strip>>;
    gmSummary: z.ZodOptional<z.ZodString>;
    gmTrace: z.ZodOptional<z.ZodObject<{
        auditId: z.ZodString;
        nodeId: z.ZodString;
        requestId: z.ZodString;
    }, z.core.$strip>>;
    handlerId: z.ZodOptional<z.ZodString>;
    inventoryDelta: z.ZodOptional<z.ZodObject<{
        ops: z.ZodDefault<z.ZodArray<z.ZodObject<{
            op: z.ZodEnum<{
                add: "add";
                remove: "remove";
                update: "update";
            }>;
            name: z.ZodString;
            kind: z.ZodEnum<{
                relic: "relic";
                consumable: "consumable";
                supplies: "supplies";
                gear: "gear";
            }>;
            description: z.ZodString;
            effect: z.ZodNullable<z.ZodOptional<z.ZodString>>;
            quantity: z.ZodNumber;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
    playerIntent: z.ZodOptional<z.ZodObject<{
        creativeSpark: z.ZodBoolean;
        handlerHints: z.ZodArray<z.ZodString>;
        beatDirective: z.ZodObject<{
            kind: z.ZodDefault<z.ZodEnum<{
                independent: "independent";
                existing: "existing";
                new: "new";
            }>>;
            summary: z.ZodString;
            targetBeatId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        }, z.core.$strip>;
        intentSummary: z.ZodString;
        intentType: z.ZodEnum<{
            action: "action";
            inquiry: "inquiry";
            clarification: "clarification";
            possibility: "possibility";
            planning: "planning";
            reflection: "reflection";
            wrap: "wrap";
        }>;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        routerRationale: z.ZodString;
        tone: z.ZodString;
    }, z.core.$strip>>;
    resolvedIntentConfidence: z.ZodOptional<z.ZodNumber>;
    resolvedIntentType: z.ZodOptional<z.ZodEnum<{
        action: "action";
        inquiry: "inquiry";
        clarification: "clarification";
        possibility: "possibility";
        planning: "planning";
        reflection: "reflection";
        wrap: "wrap";
    }>>;
    skillCheckPlan: z.ZodOptional<z.ZodObject<{
        advantage: z.ZodString;
        complicationSeeds: z.ZodArray<z.ZodString>;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        riskLevel: z.ZodEnum<{
            controlled: "controlled";
            standard: "standard";
            risky: "risky";
            desperate: "desperate";
        }>;
        attribute: z.ZodEnum<{
            vitality: "vitality";
            finesse: "finesse";
            focus: "focus";
            resolve: "resolve";
            attunement: "attunement";
            ingenuity: "ingenuity";
            presence: "presence";
        }>;
        skill: z.ZodString;
        requiresCheck: z.ZodBoolean;
        creativeSpark: z.ZodBoolean;
    }, z.core.$strip>>;
    skillCheckResult: z.ZodOptional<z.ZodObject<{
        advantage: z.ZodBoolean;
        checkId: z.ZodString;
        chronicleId: z.ZodString;
        dieSum: z.ZodNumber;
        disadvantage: z.ZodBoolean;
        margin: z.ZodNumber;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        newMomentum: z.ZodNumber;
        outcomeTier: z.ZodEnum<{
            breakthrough: "breakthrough";
            advance: "advance";
            stall: "stall";
            regress: "regress";
            collapse: "collapse";
        }>;
        totalModifier: z.ZodNumber;
    }, z.core.$strip>>;
    systemMessage: z.ZodOptional<z.ZodObject<{
        content: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        role: z.ZodEnum<{
            player: "player";
            gm: "gm";
            system: "system";
        }>;
    }, z.core.$strip>>;
    worldDeltaTags: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const TurnProgressEventSchema: z.ZodObject<{
    chronicleId: z.ZodString;
    jobId: z.ZodString;
    nodeId: z.ZodString;
    payload: z.ZodOptional<z.ZodObject<{
        advancesTimeline: z.ZodOptional<z.ZodBoolean>;
        beatTracker: z.ZodOptional<z.ZodObject<{
            focusBeatId: z.ZodNullable<z.ZodString>;
            newBeat: z.ZodNullable<z.ZodObject<{
                title: z.ZodString;
                description: z.ZodString;
            }, z.core.$strip>>;
            updates: z.ZodArray<z.ZodObject<{
                beatId: z.ZodString;
                changeKind: z.ZodEnum<{
                    advance: "advance";
                    resolve: "resolve";
                }>;
                description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
                status: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
                    in_progress: "in_progress";
                    succeeded: "succeeded";
                    failed: "failed";
                }>>>;
            }, z.core.$strip>>;
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        chronicleShouldClose: z.ZodOptional<z.ZodBoolean>;
        executedNodes: z.ZodOptional<z.ZodArray<z.ZodString>>;
        failure: z.ZodOptional<z.ZodBoolean>;
        gmMessage: z.ZodOptional<z.ZodObject<{
            content: z.ZodString;
            id: z.ZodString;
            metadata: z.ZodObject<{
                tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
                timestamp: z.ZodDefault<z.ZodNumber>;
            }, z.core.$strip>;
            role: z.ZodEnum<{
                player: "player";
                gm: "gm";
                system: "system";
            }>;
        }, z.core.$strip>>;
        gmSummary: z.ZodOptional<z.ZodString>;
        gmTrace: z.ZodOptional<z.ZodObject<{
            auditId: z.ZodString;
            nodeId: z.ZodString;
            requestId: z.ZodString;
        }, z.core.$strip>>;
        handlerId: z.ZodOptional<z.ZodString>;
        inventoryDelta: z.ZodOptional<z.ZodObject<{
            ops: z.ZodDefault<z.ZodArray<z.ZodObject<{
                op: z.ZodEnum<{
                    add: "add";
                    remove: "remove";
                    update: "update";
                }>;
                name: z.ZodString;
                kind: z.ZodEnum<{
                    relic: "relic";
                    consumable: "consumable";
                    supplies: "supplies";
                    gear: "gear";
                }>;
                description: z.ZodString;
                effect: z.ZodNullable<z.ZodOptional<z.ZodString>>;
                quantity: z.ZodNumber;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
        playerIntent: z.ZodOptional<z.ZodObject<{
            creativeSpark: z.ZodBoolean;
            handlerHints: z.ZodArray<z.ZodString>;
            beatDirective: z.ZodObject<{
                kind: z.ZodDefault<z.ZodEnum<{
                    independent: "independent";
                    existing: "existing";
                    new: "new";
                }>>;
                summary: z.ZodString;
                targetBeatId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
            }, z.core.$strip>;
            intentSummary: z.ZodString;
            intentType: z.ZodEnum<{
                action: "action";
                inquiry: "inquiry";
                clarification: "clarification";
                possibility: "possibility";
                planning: "planning";
                reflection: "reflection";
                wrap: "wrap";
            }>;
            metadata: z.ZodObject<{
                tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
                timestamp: z.ZodDefault<z.ZodNumber>;
            }, z.core.$strip>;
            routerRationale: z.ZodString;
            tone: z.ZodString;
        }, z.core.$strip>>;
        resolvedIntentConfidence: z.ZodOptional<z.ZodNumber>;
        resolvedIntentType: z.ZodOptional<z.ZodEnum<{
            action: "action";
            inquiry: "inquiry";
            clarification: "clarification";
            possibility: "possibility";
            planning: "planning";
            reflection: "reflection";
            wrap: "wrap";
        }>>;
        skillCheckPlan: z.ZodOptional<z.ZodObject<{
            advantage: z.ZodString;
            complicationSeeds: z.ZodArray<z.ZodString>;
            metadata: z.ZodObject<{
                tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
                timestamp: z.ZodDefault<z.ZodNumber>;
            }, z.core.$strip>;
            riskLevel: z.ZodEnum<{
                controlled: "controlled";
                standard: "standard";
                risky: "risky";
                desperate: "desperate";
            }>;
            attribute: z.ZodEnum<{
                vitality: "vitality";
                finesse: "finesse";
                focus: "focus";
                resolve: "resolve";
                attunement: "attunement";
                ingenuity: "ingenuity";
                presence: "presence";
            }>;
            skill: z.ZodString;
            requiresCheck: z.ZodBoolean;
            creativeSpark: z.ZodBoolean;
        }, z.core.$strip>>;
        skillCheckResult: z.ZodOptional<z.ZodObject<{
            advantage: z.ZodBoolean;
            checkId: z.ZodString;
            chronicleId: z.ZodString;
            dieSum: z.ZodNumber;
            disadvantage: z.ZodBoolean;
            margin: z.ZodNumber;
            metadata: z.ZodObject<{
                tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
                timestamp: z.ZodDefault<z.ZodNumber>;
            }, z.core.$strip>;
            newMomentum: z.ZodNumber;
            outcomeTier: z.ZodEnum<{
                breakthrough: "breakthrough";
                advance: "advance";
                stall: "stall";
                regress: "regress";
                collapse: "collapse";
            }>;
            totalModifier: z.ZodNumber;
        }, z.core.$strip>>;
        systemMessage: z.ZodOptional<z.ZodObject<{
            content: z.ZodString;
            id: z.ZodString;
            metadata: z.ZodObject<{
                tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
                timestamp: z.ZodDefault<z.ZodNumber>;
            }, z.core.$strip>;
            role: z.ZodEnum<{
                player: "player";
                gm: "gm";
                system: "system";
            }>;
        }, z.core.$strip>>;
        worldDeltaTags: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
    status: z.ZodEnum<{
        error: "error";
        success: "success";
        start: "start";
    }>;
    step: z.ZodNumber;
    total: z.ZodNumber;
    turnSequence: z.ZodNumber;
}, z.core.$strip>;
export type TurnProgressPayload = z.infer<typeof TurnProgressPayloadSchema>;
export type TurnProgressEvent = z.infer<typeof TurnProgressEventSchema>;
