import { z } from 'zod';
export declare const TurnSchema: z.ZodObject<{
    advancesTimeline: z.ZodOptional<z.ZodBoolean>;
    beatTracker: z.ZodOptional<z.ZodObject<{
        focusBeatId: z.ZodNullable<z.ZodString>;
        newBeat: z.ZodNullable<z.ZodObject<{
            title: z.ZodString;
            description: z.ZodString;
        }, z.core.$strip>>;
        updates: z.ZodArray<z.ZodObject<{
            beatId: z.ZodString;
            changeKind: z.ZodEnum<{
                advance: "advance";
                resolve: "resolve";
            }>;
            description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
            status: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
                in_progress: "in_progress";
                succeeded: "succeeded";
                failed: "failed";
            }>>>;
        }, z.core.$strip>>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
    chronicleId: z.ZodString;
    entityOffered: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        slug: z.ZodString;
        name: z.ZodString;
        kind: z.ZodString;
        subkind: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        status: z.ZodOptional<z.ZodString>;
        tags: z.ZodArray<z.ZodString>;
        loreFragments: z.ZodArray<z.ZodObject<{
            slug: z.ZodString;
            title: z.ZodString;
            summary: z.ZodString;
            tags: z.ZodArray<z.ZodString>;
        }, z.core.$strip>>;
        score: z.ZodNumber;
    }, z.core.$strip>>>;
    entityUsage: z.ZodOptional<z.ZodArray<z.ZodObject<{
        entityId: z.ZodString;
        entitySlug: z.ZodString;
        tags: z.ZodArray<z.ZodString>;
        usage: z.ZodEnum<{
            unused: "unused";
            mentioned: "mentioned";
            central: "central";
        }>;
        emergentTags: z.ZodNullable<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
    executedNodes: z.ZodOptional<z.ZodArray<z.ZodString>>;
    failure: z.ZodBoolean;
    gmResponse: z.ZodOptional<z.ZodObject<{
        content: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        role: z.ZodEnum<{
            player: "player";
            gm: "gm";
            system: "system";
        }>;
    }, z.core.$strip>>;
    gmSummary: z.ZodOptional<z.ZodString>;
    gmTrace: z.ZodOptional<z.ZodObject<{
        auditId: z.ZodString;
        nodeId: z.ZodString;
        requestId: z.ZodString;
    }, z.core.$strip>>;
    handlerId: z.ZodOptional<z.ZodString>;
    id: z.ZodString;
    inventoryDelta: z.ZodOptional<z.ZodObject<{
        ops: z.ZodDefault<z.ZodArray<z.ZodObject<{
            op: z.ZodEnum<{
                add: "add";
                remove: "remove";
                update: "update";
            }>;
            name: z.ZodString;
            kind: z.ZodEnum<{
                relic: "relic";
                consumable: "consumable";
                supplies: "supplies";
                gear: "gear";
            }>;
            description: z.ZodString;
            effect: z.ZodNullable<z.ZodOptional<z.ZodString>>;
            quantity: z.ZodNumber;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
    playerIntent: z.ZodOptional<z.ZodObject<{
        creativeSpark: z.ZodBoolean;
        handlerHints: z.ZodArray<z.ZodString>;
        beatDirective: z.ZodObject<{
            kind: z.ZodDefault<z.ZodEnum<{
                independent: "independent";
                existing: "existing";
                new: "new";
            }>>;
            summary: z.ZodString;
            targetBeatId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        }, z.core.$strip>;
        intentSummary: z.ZodString;
        intentType: z.ZodEnum<{
            action: "action";
            inquiry: "inquiry";
            clarification: "clarification";
            possibility: "possibility";
            planning: "planning";
            reflection: "reflection";
            wrap: "wrap";
        }>;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        routerRationale: z.ZodString;
        tone: z.ZodString;
    }, z.core.$strip>>;
    playerMessage: z.ZodObject<{
        content: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        role: z.ZodEnum<{
            player: "player";
            gm: "gm";
            system: "system";
        }>;
    }, z.core.$strip>;
    resolvedIntentConfidence: z.ZodOptional<z.ZodNumber>;
    resolvedIntentType: z.ZodOptional<z.ZodEnum<{
        action: "action";
        inquiry: "inquiry";
        clarification: "clarification";
        possibility: "possibility";
        planning: "planning";
        reflection: "reflection";
        wrap: "wrap";
    }>>;
    skillCheckPlan: z.ZodOptional<z.ZodObject<{
        advantage: z.ZodString;
        complicationSeeds: z.ZodArray<z.ZodString>;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        riskLevel: z.ZodEnum<{
            controlled: "controlled";
            standard: "standard";
            risky: "risky";
            desperate: "desperate";
        }>;
        attribute: z.ZodEnum<{
            vitality: "vitality";
            finesse: "finesse";
            focus: "focus";
            resolve: "resolve";
            attunement: "attunement";
            ingenuity: "ingenuity";
            presence: "presence";
        }>;
        skill: z.ZodString;
        requiresCheck: z.ZodBoolean;
        creativeSpark: z.ZodBoolean;
    }, z.core.$strip>>;
    skillCheckResult: z.ZodOptional<z.ZodObject<{
        advantage: z.ZodBoolean;
        checkId: z.ZodString;
        chronicleId: z.ZodString;
        dieSum: z.ZodNumber;
        disadvantage: z.ZodBoolean;
        margin: z.ZodNumber;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        newMomentum: z.ZodNumber;
        outcomeTier: z.ZodEnum<{
            breakthrough: "breakthrough";
            advance: "advance";
            stall: "stall";
            regress: "regress";
            collapse: "collapse";
        }>;
        totalModifier: z.ZodNumber;
    }, z.core.$strip>>;
    systemMessage: z.ZodOptional<z.ZodObject<{
        content: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodObject<{
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            timestamp: z.ZodDefault<z.ZodNumber>;
        }, z.core.$strip>;
        role: z.ZodEnum<{
            player: "player";
            gm: "gm";
            system: "system";
        }>;
    }, z.core.$strip>>;
    turnSequence: z.ZodNumber;
    worldDeltaTags: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export type Turn = z.infer<typeof TurnSchema>;
