DROP SCHEMA IF EXISTS ops CASCADE;
DROP SCHEMA IF EXISTS app CASCADE;

DROP TABLE IF EXISTS chronicle_session_state CASCADE;
DROP TABLE IF EXISTS chronicle_turn CASCADE;
DROP TABLE IF EXISTS lore_fragment CASCADE;
DROP TABLE IF EXISTS chronicle CASCADE;
DROP TABLE IF EXISTS edge CASCADE;
DROP TABLE IF EXISTS ingest_batch CASCADE;
DROP TABLE IF EXISTS entity CASCADE;
DROP TABLE IF EXISTS character CASCADE;
DROP TABLE IF EXISTS node CASCADE;
DROP TABLE IF EXISTS world_relationship_rule CASCADE;
DROP TABLE IF EXISTS world_relationship_kind CASCADE;
DROP TABLE IF EXISTS world_kind_status CASCADE;
DROP TABLE IF EXISTS world_subkind CASCADE;
DROP TABLE IF EXISTS world_kind CASCADE;
DROP TABLE IF EXISTS world_prominence CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
