import { z } from 'zod';
export declare const AUDIT_REVIEW_TAGS: readonly ["coverage_gap", "hallucination", "tone_mismatch", "style_error", "instruction_ignored", "context_misuse", "verbosity_issue", "output_safety_concern", "format_violation"];
export declare const AUDIT_REVIEW_SEVERITIES: readonly ["info", "minor", "major", "critical"];
export declare const AUDIT_REVIEW_STATUSES: readonly ["unreviewed", "in_progress", "completed"];
export type AuditReviewTag = (typeof AUDIT_REVIEW_TAGS)[number];
export type AuditReviewSeverity = (typeof AUDIT_REVIEW_SEVERITIES)[number];
export type AuditReviewStatus = (typeof AUDIT_REVIEW_STATUSES)[number];
export declare const PLAYER_FEEDBACK_SENTIMENTS: readonly ["positive", "neutral", "negative"];
export type PlayerFeedbackSentiment = (typeof PLAYER_FEEDBACK_SENTIMENTS)[number];
export declare const PlayerFeedbackRecordSchema: z.ZodObject<{
    auditId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    chronicleId: z.ZodString;
    comment: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    createdAt: z.ZodString;
    expectedIntentType: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        action: "action";
        inquiry: "inquiry";
        clarification: "clarification";
        possibility: "possibility";
        planning: "planning";
        reflection: "reflection";
        wrap: "wrap";
    }>>>;
    expectedInventoryDelta: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    expectedInventoryNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    expectedLocationChange: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    expectedLocationNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    expectedSkillCheck: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
    expectedSkillNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    gmEntryId: z.ZodString;
    groupId: z.ZodString;
    id: z.ZodString;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    playerId: z.ZodString;
    sentiment: z.ZodEnum<{
        positive: "positive";
        neutral: "neutral";
        negative: "negative";
    }>;
    turnId: z.ZodString;
    turnSequence: z.ZodNumber;
    updatedAt: z.ZodString;
}, z.core.$strip>;
export type PlayerFeedbackRecord = z.infer<typeof PlayerFeedbackRecordSchema>;
export declare const LlmTraceSchema: z.ZodObject<{
    auditId: z.ZodString;
    nodeId: z.ZodString;
    requestId: z.ZodString;
}, z.core.$strip>;
export type LlmTrace = z.infer<typeof LlmTraceSchema>;
export declare const AuditReviewRecordSchema: z.ZodObject<{
    auditId: z.ZodString;
    completedAt: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    createdAt: z.ZodString;
    draftAt: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    id: z.ZodString;
    nodeId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    reviewerId: z.ZodString;
    reviewerName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    status: z.ZodEnum<{
        in_progress: "in_progress";
        unreviewed: "unreviewed";
        completed: "completed";
    }>;
    storageKey: z.ZodString;
    tags: z.ZodDefault<z.ZodArray<z.ZodEnum<{
        coverage_gap: "coverage_gap";
        hallucination: "hallucination";
        tone_mismatch: "tone_mismatch";
        style_error: "style_error";
        instruction_ignored: "instruction_ignored";
        context_misuse: "context_misuse";
        verbosity_issue: "verbosity_issue";
        output_safety_concern: "output_safety_concern";
        format_violation: "format_violation";
    }>>>;
    templateId: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        "action-resolver": "action-resolver";
        "wrap-resolver": "wrap-resolver";
        "beat-tracker": "beat-tracker";
        "check-planner": "check-planner";
        "chronicle-seed": "chronicle-seed";
        "clarification-responder": "clarification-responder";
        "entity-judge": "entity-judge";
        "gm-summary": "gm-summary";
        "inquiry-describer": "inquiry-describer";
        "intent-beat-detector": "intent-beat-detector";
        "intent-classifier": "intent-classifier";
        "inventory-delta": "inventory-delta";
        "location-delta": "location-delta";
        "lore-judge": "lore-judge";
        "planning-narrator": "planning-narrator";
        "possibility-advisor": "possibility-advisor";
        "reflection-weaver": "reflection-weaver";
    }>>>;
    updatedAt: z.ZodString;
}, z.core.$strip>;
export type AuditReviewRecord = z.infer<typeof AuditReviewRecordSchema>;
export declare const AuditLogEntrySchema: z.ZodObject<{
    createdAt: z.ZodString;
    createdAtMs: z.ZodNumber;
    id: z.ZodString;
    metadata: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>>;
    nodeId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    playerFeedback: z.ZodOptional<z.ZodArray<z.ZodObject<{
        auditId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        chronicleId: z.ZodString;
        comment: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        createdAt: z.ZodString;
        expectedIntentType: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
            action: "action";
            inquiry: "inquiry";
            clarification: "clarification";
            possibility: "possibility";
            planning: "planning";
            reflection: "reflection";
            wrap: "wrap";
        }>>>;
        expectedInventoryDelta: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
        expectedInventoryNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        expectedLocationChange: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
        expectedLocationNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        expectedSkillCheck: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
        expectedSkillNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        gmEntryId: z.ZodString;
        groupId: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        playerId: z.ZodString;
        sentiment: z.ZodEnum<{
            positive: "positive";
            neutral: "neutral";
            negative: "negative";
        }>;
        turnId: z.ZodString;
        turnSequence: z.ZodNumber;
        updatedAt: z.ZodString;
    }, z.core.$strip>>>;
    playerId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    providerId: z.ZodString;
    request: z.ZodRecord<z.ZodString, z.ZodAny>;
    requestContextId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    response: z.ZodAny;
    storageKey: z.ZodString;
}, z.core.$strip>;
export type AuditLogEntry = z.infer<typeof AuditLogEntrySchema>;
export declare const AuditQueueItemSchema: z.ZodObject<{
    auditId: z.ZodString;
    chronicleId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    createdAt: z.ZodString;
    createdAtMs: z.ZodNumber;
    groupId: z.ZodString;
    nodeId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    playerFeedback: z.ZodOptional<z.ZodArray<z.ZodObject<{
        auditId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        chronicleId: z.ZodString;
        comment: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        createdAt: z.ZodString;
        expectedIntentType: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
            action: "action";
            inquiry: "inquiry";
            clarification: "clarification";
            possibility: "possibility";
            planning: "planning";
            reflection: "reflection";
            wrap: "wrap";
        }>>>;
        expectedInventoryDelta: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
        expectedInventoryNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        expectedLocationChange: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
        expectedLocationNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        expectedSkillCheck: z.ZodNullable<z.ZodOptional<z.ZodBoolean>>;
        expectedSkillNotes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
        gmEntryId: z.ZodString;
        groupId: z.ZodString;
        id: z.ZodString;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        playerId: z.ZodString;
        sentiment: z.ZodEnum<{
            positive: "positive";
            neutral: "neutral";
            negative: "negative";
        }>;
        turnId: z.ZodString;
        turnSequence: z.ZodNumber;
        updatedAt: z.ZodString;
    }, z.core.$strip>>>;
    playerId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    providerId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    requestContextId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    reviewerId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    reviewerName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    status: z.ZodEnum<{
        in_progress: "in_progress";
        unreviewed: "unreviewed";
        completed: "completed";
    }>;
    storageKey: z.ZodString;
    tags: z.ZodArray<z.ZodEnum<{
        coverage_gap: "coverage_gap";
        hallucination: "hallucination";
        tone_mismatch: "tone_mismatch";
        style_error: "style_error";
        instruction_ignored: "instruction_ignored";
        context_misuse: "context_misuse";
        verbosity_issue: "verbosity_issue";
        output_safety_concern: "output_safety_concern";
        format_violation: "format_violation";
    }>>;
    templateId: z.ZodNullable<z.ZodOptional<z.ZodEnum<{
        "action-resolver": "action-resolver";
        "wrap-resolver": "wrap-resolver";
        "beat-tracker": "beat-tracker";
        "check-planner": "check-planner";
        "chronicle-seed": "chronicle-seed";
        "clarification-responder": "clarification-responder";
        "entity-judge": "entity-judge";
        "gm-summary": "gm-summary";
        "inquiry-describer": "inquiry-describer";
        "intent-beat-detector": "intent-beat-detector";
        "intent-classifier": "intent-classifier";
        "inventory-delta": "inventory-delta";
        "location-delta": "location-delta";
        "lore-judge": "lore-judge";
        "planning-narrator": "planning-narrator";
        "possibility-advisor": "possibility-advisor";
        "reflection-weaver": "reflection-weaver";
    }>>>;
    turnId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    turnSequence: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
}, z.core.$strip>;
export type AuditQueueItem = z.infer<typeof AuditQueueItemSchema>;
export declare const AuditProposalRecordSchema: z.ZodObject<{
    confidence: z.ZodNumber;
    createdAt: z.ZodString;
    id: z.ZodString;
    linkedReviewIds: z.ZodDefault<z.ZodArray<z.ZodString>>;
    rationale: z.ZodString;
    reviewCount: z.ZodNumber;
    severity: z.ZodEnum<{
        info: "info";
        minor: "minor";
        major: "major";
        critical: "critical";
    }>;
    suggestedChange: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    summary: z.ZodString;
    tags: z.ZodDefault<z.ZodArray<z.ZodEnum<{
        coverage_gap: "coverage_gap";
        hallucination: "hallucination";
        tone_mismatch: "tone_mismatch";
        style_error: "style_error";
        instruction_ignored: "instruction_ignored";
        context_misuse: "context_misuse";
        verbosity_issue: "verbosity_issue";
        output_safety_concern: "output_safety_concern";
        format_violation: "format_violation";
    }>>>;
    templateId: z.ZodEnum<{
        "action-resolver": "action-resolver";
        "wrap-resolver": "wrap-resolver";
        "beat-tracker": "beat-tracker";
        "check-planner": "check-planner";
        "chronicle-seed": "chronicle-seed";
        "clarification-responder": "clarification-responder";
        "entity-judge": "entity-judge";
        "gm-summary": "gm-summary";
        "inquiry-describer": "inquiry-describer";
        "intent-beat-detector": "intent-beat-detector";
        "intent-classifier": "intent-classifier";
        "inventory-delta": "inventory-delta";
        "location-delta": "location-delta";
        "lore-judge": "lore-judge";
        "planning-narrator": "planning-narrator";
        "possibility-advisor": "possibility-advisor";
        "reflection-weaver": "reflection-weaver";
    }>;
}, z.core.$strip>;
export type AuditProposalRecord = z.infer<typeof AuditProposalRecordSchema>;
