import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PromptTemplateIds } from '@glass-frontier/dto';

/**
 * Turns the authored prompt templates into the seed that loads them.
 *
 * `packages/app/templates` is the only place a prompt body is written. The
 * runtime reads bodies from `app.prompt_template`, so that table is filled from
 * this generated file — never from SQL anyone edits by hand. Generation runs
 * before the seed is applied, locally and in the deploy alike, which is what
 * keeps the running prompt equal to the checked-in one.
 *
 * Player overrides live in `app.prompt_template_override` and are not touched
 * here; only the official body a player has not overridden comes from this.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const TEMPLATE_DIR = path.resolve(__dirname, '../packages/app/templates');
export const GENERATED_SEED_PATH = path.resolve(
  __dirname,
  '../db/migrations/seed/002_prompt_templates.sql'
);

/** Postgres dollar quoting: the tag must not appear inside the body it wraps. */
const QUOTE_TAG = '$prompt$';

const templateIds = new Set<string>(PromptTemplateIds);

const readTemplateBodies = async (): Promise<Map<string, string>> => {
  const entries = await readdir(TEMPLATE_DIR, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.hbs'))
    .map((entry) => entry.name)
    .sort();

  const bodies = new Map<string, string>();
  for (const filename of files) {
    const id = path.basename(filename, '.hbs');
    if (!templateIds.has(id)) {
      throw new Error(
        `${filename} has no entry in PromptTemplateIds. Add the id to the descriptor registry or delete the file.`
      );
    }
    const body = await readFile(path.join(TEMPLATE_DIR, filename), 'utf8');
    if (body.includes(QUOTE_TAG)) {
      throw new Error(`${filename} contains ${QUOTE_TAG}, which would end its SQL quoting.`);
    }
    bodies.set(id, body.trim());
  }

  const missing = [...templateIds].filter((id) => !bodies.has(id)).sort();
  if (missing.length > 0) {
    throw new Error(`No template file for: ${missing.join(', ')}. Expected ${TEMPLATE_DIR}/<id>.hbs.`);
  }
  return bodies;
};

/**
 * `updated_at` moves only when the body does, so the timestamp the template
 * drawer shows means "last changed" rather than "last deployed".
 */
const toSeedSql = (bodies: Map<string, string>): string => {
  const values = [...bodies.entries()]
    .map(([id, body]) => `  ('${id}', ${QUOTE_TAG}${body}${QUOTE_TAG})`)
    .join(',\n');
  const idList = [...bodies.keys()].map((id) => `'${id}'`).join(', ');
  return `-- Generated by scripts/generatePromptTemplateSeed.ts from packages/app/templates.
-- Do not edit: edit the .hbs file and regenerate.

INSERT INTO app.prompt_template (id, body)
VALUES
${values}
ON CONFLICT (id) DO UPDATE SET
  body = EXCLUDED.body,
  updated_at = now()
WHERE app.prompt_template.body IS DISTINCT FROM EXCLUDED.body;

DELETE FROM app.prompt_template WHERE id NOT IN (${idList});
`;
};

/** Writes the seed file and returns the ids it covers. */
export const generatePromptTemplateSeed = async (): Promise<string[]> => {
  const bodies = await readTemplateBodies();
  await writeFile(GENERATED_SEED_PATH, toSeedSql(bodies), 'utf8');
  return [...bodies.keys()];
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const ids = await generatePromptTemplateSeed();
  console.log(`[prompt-templates] generated ${GENERATED_SEED_PATH} with ${ids.length} templates`);
}
