import { z } from 'zod';

export const PromptTemplateIds = [
  'action-resolver',
  'agent-action-resolver',
  'agent-clarification-responder',
  'agent-inquiry-describer',
  'agent-planning-narrator',
  'agent-possibility-advisor',
  'agent-reflection-weaver',
  'agent-wrap-resolver',
  'wrap-resolver',
  'canon-extractor',
  'canon-resolver',
  'check-planner',
  'chronicle-opening',
  'chronicle-seed',
  'clarification-responder',
  'entity-judge',
  'entity-reference-resolver',
  'entity-summarizer',
  'inquiry-describer',
  'intent-classifier',
  'inventory-delta',
  'local-continuity',
  'location-delta',
  'planning-narrator',
  'possibility-advisor',
  'reflection-weaver',
  'scene-battle',
  'scene-chase',
  'scene-dialog',
  'scene-hunt',
  'scene-search',
  'thread-position',
] as const;

export type PromptTemplateId = (typeof PromptTemplateIds)[number];

export const PromptTemplateDescriptor = z.object({
  description: z.string().min(1),
  id: z.enum(PromptTemplateIds),
  label: z.string().min(1),
  officialObjectKey: z.string().min(1),
  supportsVariants: z.boolean().default(true),
});

export type PromptTemplateDescriptor = z.infer<typeof PromptTemplateDescriptor>;

export const PROMPT_TEMPLATE_DESCRIPTORS: Record<PromptTemplateId, PromptTemplateDescriptor> = {
  'action-resolver': {
    description: 'Resolves decisive player actions with consequences and hooks.',
    id: 'action-resolver',
    label: 'Action Resolver',
    officialObjectKey: 'official/action-resolver.hbs',
    supportsVariants: true,
  },
  'agent-action-resolver': {
    description: 'Agentic action narration: retrieves world material, then resolves the action.',
    id: 'agent-action-resolver',
    label: 'Agent Action Resolver',
    officialObjectKey: 'official/agent-action-resolver.hbs',
    supportsVariants: true,
  },
  'agent-clarification-responder': {
    description: 'Agentic factual answers about the current scene, with retrieval.',
    id: 'agent-clarification-responder',
    label: 'Agent Clarification Responder',
    officialObjectKey: 'official/agent-clarification-responder.hbs',
    supportsVariants: true,
  },
  'agent-inquiry-describer': {
    description: 'Agentic sensory description: retrieves what the question touches, then describes.',
    id: 'agent-inquiry-describer',
    label: 'Agent Inquiry Describer',
    officialObjectKey: 'official/agent-inquiry-describer.hbs',
    supportsVariants: true,
  },
  'agent-planning-narrator': {
    description: 'Agentic preparation and travel montages grounded in retrieved canon.',
    id: 'agent-planning-narrator',
    label: 'Agent Planning Narrator',
    officialObjectKey: 'official/agent-planning-narrator.hbs',
    supportsVariants: true,
  },
  'agent-possibility-advisor': {
    description: 'Agentic option briefings grounded in retrieved canon.',
    id: 'agent-possibility-advisor',
    label: 'Agent Possibility Advisor',
    officialObjectKey: 'official/agent-possibility-advisor.hbs',
    supportsVariants: true,
  },
  'agent-reflection-weaver': {
    description: 'Agentic reflective interludes; retrieval only when a fact is at stake.',
    id: 'agent-reflection-weaver',
    label: 'Agent Reflection Weaver',
    officialObjectKey: 'official/agent-reflection-weaver.hbs',
    supportsVariants: true,
  },
  'agent-wrap-resolver': {
    description: 'Agentic chronicle-closing narration with retrieval.',
    id: 'agent-wrap-resolver',
    label: 'Agent Wrap Resolver',
    officialObjectKey: 'official/agent-wrap-resolver.hbs',
    supportsVariants: true,
  },
  'canon-extractor': {
    description: 'Extracts canon-worthy named entities and lore from a closed chronicle.',
    id: 'canon-extractor',
    label: 'Canon Extractor',
    officialObjectKey: 'official/canon-extractor.hbs',
    supportsVariants: true,
  },
  'canon-resolver': {
    description: 'Decides whether an extracted entity merges into existing canon or stands alone.',
    id: 'canon-resolver',
    label: 'Canon Resolver',
    officialObjectKey: 'official/canon-resolver.hbs',
    supportsVariants: true,
  },
  'check-planner': {
    description: 'Determines mechanical framing for risky actions and complications.',
    id: 'check-planner',
    label: 'Check Planner',
    officialObjectKey: 'official/check-planner.hbs',
    supportsVariants: true,
  },
  'chronicle-opening': {
    description: 'Writes the grounded first GM message for a newly created chronicle.',
    id: 'chronicle-opening',
    label: 'Chronicle Opening',
    officialObjectKey: 'official/chronicle-opening.hbs',
    supportsVariants: true,
  },
  'chronicle-seed': {
    description: 'Generates short chronicle hooks based on a location and tone prompt.',
    id: 'chronicle-seed',
    label: 'Chronicle Seeds',
    officialObjectKey: 'official/chronicle-seed.hbs',
    supportsVariants: true,
  },
  'clarification-responder': {
    description: 'Answers short factual clarification questions crisply.',
    id: 'clarification-responder',
    label: 'Clarification Responder',
    officialObjectKey: 'official/clarification-responder.hbs',
    supportsVariants: true,
  },
  'entity-judge': {
    description: 'Classifies how entities were involved in the GM response.',
    id: 'entity-judge',
    label: 'Entity Judge',
    officialObjectKey: 'official/entity-judge.hbs',
    supportsVariants: false,
  },
  'entity-reference-resolver': {
    description: 'Maps vague transcript wording to established entities already near the scene.',
    id: 'entity-reference-resolver',
    label: 'Entity Reference Resolver',
    officialObjectKey: 'official/entity-reference-resolver.hbs',
    supportsVariants: false,
  },
  'entity-summarizer': {
    description: 'Recomputes what a play-born entity is from its accumulated lore and edges.',
    id: 'entity-summarizer',
    label: 'Entity Summarizer',
    officialObjectKey: 'official/entity-summarizer.hbs',
    supportsVariants: true,
  },
  'inquiry-describer': {
    description: 'Provides sensory-rich scene description for inquiry turns.',
    id: 'inquiry-describer',
    label: 'Inquiry Describer',
    officialObjectKey: 'official/inquiry-describer.hbs',
    supportsVariants: true,
  },
  'intent-classifier': {
    description: 'Parses the player\'s utterance into actionable intent metadata.',
    id: 'intent-classifier',
    label: 'Intent Classifier',
    officialObjectKey: 'official/intent-classifier.hbs',
    supportsVariants: true,
  },
  'inventory-delta': {
    description: 'Applies deterministic inventory changes between the GM narration and character save.',
    id: 'inventory-delta',
    label: 'Inventory Delta',
    officialObjectKey: 'official/inventory-delta.hbs',
    supportsVariants: true,
  },
  'local-continuity': {
    description: 'Updates a short prose note about the immediate local situation.',
    id: 'local-continuity',
    label: 'Local Continuity',
    officialObjectKey: 'official/local-continuity.hbs',
    supportsVariants: true,
  },
  'location-delta': {
    description: 'Records a location change only when completed narration establishes arrival.',
    id: 'location-delta',
    label: 'Location Delta',
    officialObjectKey: 'official/location-delta.hbs',
    supportsVariants: true,
  },
  'planning-narrator': {
    description: 'Summarizes transitional planning/prep scenes with light deltas.',
    id: 'planning-narrator',
    label: 'Planning Narrator',
    officialObjectKey: 'official/planning-narrator.hbs',
    supportsVariants: true,
  },
  'possibility-advisor': {
    description: 'Enumerates viable options, costs, and risks without resolving them.',
    id: 'possibility-advisor',
    label: 'Possibility Advisor',
    officialObjectKey: 'official/possibility-advisor.hbs',
    supportsVariants: true,
  },
  'reflection-weaver': {
    description: 'Crafts introspective reflection prose without state changes.',
    id: 'reflection-weaver',
    label: 'Reflection Weaver',
    officialObjectKey: 'official/reflection-weaver.hbs',
    supportsVariants: true,
  },
  'scene-battle': {
    description: 'Applies battle-specific intent, check, narration, and completion rules.',
    id: 'scene-battle',
    label: 'Scene: Battle',
    officialObjectKey: 'official/scene-battle.hbs',
    supportsVariants: true,
  },
  'scene-chase': {
    description: 'Applies chase-specific intent, check, narration, and completion rules.',
    id: 'scene-chase',
    label: 'Scene: Chase',
    officialObjectKey: 'official/scene-chase.hbs',
    supportsVariants: true,
  },
  'scene-dialog': {
    description: 'Applies dialog-specific intent, check, narration, and completion rules.',
    id: 'scene-dialog',
    label: 'Scene: Dialog',
    officialObjectKey: 'official/scene-dialog.hbs',
    supportsVariants: true,
  },
  'scene-hunt': {
    description: 'Applies hunt-specific intent, check, narration, and completion rules.',
    id: 'scene-hunt',
    label: 'Scene: Hunt',
    officialObjectKey: 'official/scene-hunt.hbs',
    supportsVariants: true,
  },
  'scene-search': {
    description: 'Applies search-specific intent, check, narration, and completion rules.',
    id: 'scene-search',
    label: 'Scene: Search',
    officialObjectKey: 'official/scene-search.hbs',
    supportsVariants: true,
  },
  'thread-position': {
    description: 'Summarizes the player\'s new position toward the focused long-horizon goal.',
    id: 'thread-position',
    label: 'Thread Position',
    officialObjectKey: 'official/thread-position.hbs',
    supportsVariants: true,
  },
  'wrap-resolver': {
    description: 'Tries to end the story with decisive action',
    id: 'wrap-resolver',
    label: 'Wrap Resolver',
    officialObjectKey: 'official/wrap-resolver.hbs',
    supportsVariants: true,
  },
};
